name: Update GitHub Stats Images

on:
  schedule:
    - cron: '0 0 * * *' # веднъж на ден
  push:
    branches:
      - main

jobs:
  update-stats:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Generate GitHub Stats
        uses: andstor/github-readme-stats-action@v1
        with:
          username: malkotohuski
          output: github-stats.png
          theme: dracula
          hide_border: true
          show_icons: true

      - name: Generate Top Languages
        uses: andstor/github-readme-stats-action@v1
        with:
          username: malkotohuski
          output: github-top-langs.png
          theme: dracula
          hide_border: true
          layout: compact

      - name: Commit & Push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add github-stats.png github-top-langs.png
          git diff --cached --quiet || git commit -m "Update GitHub stats images"
          git push
